export const campaigns = [
  {
    slug: "so-done",
    title: "YOUR Mission: SO DONE abschalten - Jetzt unterstützen!",
    goal: 100000,
    raised: 50000,
    image: "/images/so_done.webp",
    date: "February 12th, 2025",
    category: "Business",
    organizer: {
      name: "Markus Haintz",
      avatar:
        "https://images.gofundme.com/qHJ-ziLZSXPfibSDu1yCcsBZ8vo=/128x128/https://www.gofundme.com/person/profiles/df5fffa92b0f4cd4bbd825baa62d2738_edited_photo_1735957013454.jpeg",
      location: "Cologne, Nordrhein-Westfalen",
      contactPageLink: "https://google.com",
    },
    totalDonations: 333,
    totalRecentDonations: 45,
    recentDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    topDonation: {
      name: "Max Mustermann",
      amount: 500,
      avatar: null,
    },
    firstDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    featuredSection: {
      heading: "Your easy, powerful, and trusted home for help",
      title_1: "Easy",
      subtitle_1: "Donate quickly and easily",
      title_2: "Powerful",
      subtitle_2: "Send help right to the people and causes you care about",
      title_3: "Trusted",
      subtitle_3: "Your donation is protected by our Giving Guarantee",
    },
    description: `[English Version below] Politiker zeigen Bürger wegen vermeintlicher Beleidigungen an Schwachkopfaffäre, Hausdurchsuchungen und Geldstrafen, veranlasst durch Politiker. Was kannst Du aktiv für die Meinungsfreiheit tun? Du spendest! Du spendest, was es Dir wert ist, die Welt von unlauteren Meldeportalen wie "SO DONE" zu befreien, die von Politikern zu Lasten der Bürger und der Meinungsfreiheit missbraucht werden. Rechtliche Unterstützung, aktiv wie passiv! Wir bezahlen mit eurer Unterstützung Anwälte der Opfer von "SO DONE" in aussichtsreichen Zivil- und Strafverfahren bei zulässigen Meinungsäußerungen. Wir suchen die juristischen Angriffspunkte gegen "SO DONE" und nutzen sie. Keiner verfolgt aktuell so viele Fälle gegen "SO DONE" und die Politiker dahinter wie unsere Partnerkanzlei HAINTZ legal, mit der wir eng zusammenarbeiten. Wir arbeiten aber auch mit anderen spezialisierten Anwaltskanzleien zusammen. Wir sorgen für Außenwirkung Unsere PR wirkt. Wir haben hunderte Beiträge zum Thema "SO DONE" und Co. veröffentlicht. Viele Staatsanwaltschaften/Richter/Professoren stehen dem SO-DONE-Konstrukt bereits ablehnend gegenüber. Der Wind muss sich weiter drehen, hilf uns dabei. Teilen, Teilen, Teilen. "SO DONE" wird aufgeben, wenn wir uns wehren Mit Deiner Spende sorgst Du dafür, dass wir unsere Maßnahmen gegen die unlauteren Methoden von "SO DONE" intensivieren können. Zum Hintergrund: Spätestens seit der "Schwachkopf"-Affäre um Bundeswirtschaftsminister Robert Habeck sind Strafanzeigen von bekannten Politikern gegen einfache Bürger als gesellschaftliches Problem bekannt geworden. Hausdurchsuchungen wegen Banalitäten, Strafbefehle für Meinungsäußerungen, Bereicherung durch führende Politiker – all das ist inzwischen Alltag in Deutschland. Verantwortlich hierfür sind vor allem Meldeportale, und insbesondere das FDP-nahe Meldeportal SO DONE, das mit unlauteren Methoden für abertausende Strafanzeigen gegen Bürger verantwortlich ist. Diese Kampagne soll das rechtswidrige Treiben von SO DONE und den Politikern, die mit dem Meldeportal zusammenarbeiten, beenden. Seit eineinhalb Jahren geht unser Team politisch, juristisch und medial gegen SO DONE vor. Wir haben hunderte Beiträge zum Thema SO DONE veröffentlicht, auf Social Media und auf HAINTZ media. Unsere Partnerkanzlei HAINTZ legal führt hunderte Fallakten mit Bezug zu SO DONE und weiteren rechtlichen und strafrechtlichen Verfahren von Politikern gegen Bürger. Wir arbeiten auch mit mehreren anderen Anwaltskanzleien zusammen, um das unlautere SO-DONE-Geschäftsmodell zu beenden. Wir haben das Geschäftsmodell von SO DONE juristisch schon erheblich eingeschränkt und medial reichweitenstark einer großen Öffentlichkeit bekannt gemacht. Aber das reicht uns nicht: Wir möchten das unlautere Geschäftsmodell des Meldeportals für Politiker dauerhaft und nachhaltig beenden und SO DONE abschalten. Dafür benötigen wir auch Deine Unterstützung. Wir nutzen Deine finanzielle Unterstützung u. a. dafür, Opfern von Politikeranzeigen ihre Anwälte zu bezahlen. Wir fördern aussichtsreiche Prozesse/Musterprozesse gegen SO DONE und SO DONE legal. Wir erstatten und finanzieren Strafanzeigen gegen hochrangige Politiker, Medienvertreter und Prominente in Fällen, in denen die Strafverfolgungsbehörden offenkundig mit zweierlei Maß messen. Wir nehmen SO DONE steuerrechtlich unter die Lupe. Wir unterstützen Medienprojekte zu den Themen SO DONE, Meinungsfreiheit, Strafanzeigen durch Politiker und zu Meldeportalen allgemein. Rechtlicher Hinweis: Wir können keine Spendenquittungen ausstellen. ------------------------- english Version --------------------------------- Politicians report citizens for alleged insults „Schwachkopf“-Meme-Scandal, Raids and Fines Initiated by Politicians – What Can You Do to Defend Freedom of Speech? You donate! You donate what you think it's worth to free the world from illegitime reporting platforms like SO DONE, which are abused by politicians at the expense of citizens and freedom of speech. Legal support – Both active and passive! With your support, we pay for lawyers to defend the victims of SO DONE in promising civil and criminal cases involving permissible expressions of opinion. We identify legal attack points against SO DONE and use them to fight back. More information here No one is currently pursuing as many cases against SO DONE and the politicians behind it as our partner law firm, HAINTZ legal, with whom we work closely. However, we also work together with other specialized law firms. We create public awareness Our PR efforts are effective. We have published hundreds of articles on SO DONE and similar cases. Many prosecutors, judges, and professors already reject the SO DONE construct. The tide must continue to turn – support us! Share, share, share. SO DONE will back down if we resist With your donation, you help us intensify our actions against the dishonest practices of SO DONE. Background: Since the "Schwachkopf" (Idiot) affair involving Federal Minister for Economic Affairs Robert Habeck, criminal charges filed by well-known politicians against ordinary citizens have become recognized as a societal problem. House searches over trivial matters, penalty orders for expressing opinions, and enrichment by leading politicians – all of this has become everyday reality in Germany. The main culprits behind this are reporting portals, particularly SO DONE, a platform with ties to the Free Democratic Party (FDP), which is responsible for thousands of criminal complaints against citizens through illegitime methods. This campaign aims to put an end to the unlawful activities of SO DONE and the politicians collaborating with the platform. For over a year and a half, our team has been fighting against SO DONE politically, legally, and in the media. We have published hundreds of articles on the issue, both on social media and on HAINTZ media. Our partner law firm, HAINTZ legal, manages hundreds of case files related to SO DONE and other legal and criminal proceedings involving politicians targeting citizens. We also collaborate with several other law firms to dismantle SO DONE's dishonest business model. We have already significantly restricted SO DONE’s business model through legal action and have made its activities widely known to the public. But that is not enough – we want to permanently and sustainably shut down this corrupt reporting platform for politicians. We need your support to achieve this goal. How we use your financial support: • Covering legal fees for victims of politically motivated complaints. • Supporting promising lawsuits and landmark cases against SO DONE and SO DONE legal. • Filing and funding criminal charges against high-ranking politicians, media figures, and celebrities in cases where authorities clearly apply double standards. • Investigating SO DONE from a tax law perspective. • Supporting media projects covering SO DONE, freedom of speech, political criminal charges, and reporting platforms in general. Legal Notice: We cannot issue donation receipts. Website (German), click here `,
  },
  {
    slug: "so-done-1",
    title: "YOUR Mission: SO DONE abschalten - Jetzt unterstützen!",
    goal: 100000,
    raised: 50000,
    image: "/images/so_done.webp",
    date: "February 12th, 2025",
    category: "Business",
    organizer: {
      name: "Markus Haintz",
      avatar:
        "https://images.gofundme.com/qHJ-ziLZSXPfibSDu1yCcsBZ8vo=/128x128/https://www.gofundme.com/person/profiles/df5fffa92b0f4cd4bbd825baa62d2738_edited_photo_1735957013454.jpeg",
      location: "Cologne, Nordrhein-Westfalen",
      contactPageLink: "https://google.com",
    },
    totalDonations: 333,
    totalRecentDonations: 45,
    recentDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    topDonation: {
      name: "Max Mustermann",
      amount: 500,
      avatar: null,
    },
    firstDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    featuredSection: {
      heading: "Your easy, powerful, and trusted home for help",
      title_1: "Easy",
      subtitle_1: "Donate quickly and easily",
      title_2: "Powerful",
      subtitle_2: "Send help right to the people and causes you care about",
      title_3: "Trusted",
      subtitle_3: "Your donation is protected by our Giving Guarantee",
    },
    description: `[English Version below] Politiker zeigen Bürger wegen vermeintlicher Beleidigungen an Schwachkopfaffäre, Hausdurchsuchungen und Geldstrafen, veranlasst durch Politiker. Was kannst Du aktiv für die Meinungsfreiheit tun? Du spendest! Du spendest, was es Dir wert ist, die Welt von unlauteren Meldeportalen wie "SO DONE" zu befreien, die von Politikern zu Lasten der Bürger und der Meinungsfreiheit missbraucht werden. Rechtliche Unterstützung, aktiv wie passiv! Wir bezahlen mit eurer Unterstützung Anwälte der Opfer von "SO DONE" in aussichtsreichen Zivil- und Strafverfahren bei zulässigen Meinungsäußerungen. Wir suchen die juristischen Angriffspunkte gegen "SO DONE" und nutzen sie. Keiner verfolgt aktuell so viele Fälle gegen "SO DONE" und die Politiker dahinter wie unsere Partnerkanzlei HAINTZ legal, mit der wir eng zusammenarbeiten. Wir arbeiten aber auch mit anderen spezialisierten Anwaltskanzleien zusammen. Wir sorgen für Außenwirkung Unsere PR wirkt. Wir haben hunderte Beiträge zum Thema "SO DONE" und Co. veröffentlicht. Viele Staatsanwaltschaften/Richter/Professoren stehen dem SO-DONE-Konstrukt bereits ablehnend gegenüber. Der Wind muss sich weiter drehen, hilf uns dabei. Teilen, Teilen, Teilen. "SO DONE" wird aufgeben, wenn wir uns wehren Mit Deiner Spende sorgst Du dafür, dass wir unsere Maßnahmen gegen die unlauteren Methoden von "SO DONE" intensivieren können. Zum Hintergrund: Spätestens seit der "Schwachkopf"-Affäre um Bundeswirtschaftsminister Robert Habeck sind Strafanzeigen von bekannten Politikern gegen einfache Bürger als gesellschaftliches Problem bekannt geworden. Hausdurchsuchungen wegen Banalitäten, Strafbefehle für Meinungsäußerungen, Bereicherung durch führende Politiker – all das ist inzwischen Alltag in Deutschland. Verantwortlich hierfür sind vor allem Meldeportale, und insbesondere das FDP-nahe Meldeportal SO DONE, das mit unlauteren Methoden für abertausende Strafanzeigen gegen Bürger verantwortlich ist. Diese Kampagne soll das rechtswidrige Treiben von SO DONE und den Politikern, die mit dem Meldeportal zusammenarbeiten, beenden. Seit eineinhalb Jahren geht unser Team politisch, juristisch und medial gegen SO DONE vor. Wir haben hunderte Beiträge zum Thema SO DONE veröffentlicht, auf Social Media und auf HAINTZ media. Unsere Partnerkanzlei HAINTZ legal führt hunderte Fallakten mit Bezug zu SO DONE und weiteren rechtlichen und strafrechtlichen Verfahren von Politikern gegen Bürger. Wir arbeiten auch mit mehreren anderen Anwaltskanzleien zusammen, um das unlautere SO-DONE-Geschäftsmodell zu beenden. Wir haben das Geschäftsmodell von SO DONE juristisch schon erheblich eingeschränkt und medial reichweitenstark einer großen Öffentlichkeit bekannt gemacht. Aber das reicht uns nicht: Wir möchten das unlautere Geschäftsmodell des Meldeportals für Politiker dauerhaft und nachhaltig beenden und SO DONE abschalten. Dafür benötigen wir auch Deine Unterstützung. Wir nutzen Deine finanzielle Unterstützung u. a. dafür, Opfern von Politikeranzeigen ihre Anwälte zu bezahlen. Wir fördern aussichtsreiche Prozesse/Musterprozesse gegen SO DONE und SO DONE legal. Wir erstatten und finanzieren Strafanzeigen gegen hochrangige Politiker, Medienvertreter und Prominente in Fällen, in denen die Strafverfolgungsbehörden offenkundig mit zweierlei Maß messen. Wir nehmen SO DONE steuerrechtlich unter die Lupe. Wir unterstützen Medienprojekte zu den Themen SO DONE, Meinungsfreiheit, Strafanzeigen durch Politiker und zu Meldeportalen allgemein. Rechtlicher Hinweis: Wir können keine Spendenquittungen ausstellen. ------------------------- english Version --------------------------------- Politicians report citizens for alleged insults „Schwachkopf“-Meme-Scandal, Raids and Fines Initiated by Politicians – What Can You Do to Defend Freedom of Speech? You donate! You donate what you think it's worth to free the world from illegitime reporting platforms like SO DONE, which are abused by politicians at the expense of citizens and freedom of speech. Legal support – Both active and passive! With your support, we pay for lawyers to defend the victims of SO DONE in promising civil and criminal cases involving permissible expressions of opinion. We identify legal attack points against SO DONE and use them to fight back. More information here No one is currently pursuing as many cases against SO DONE and the politicians behind it as our partner law firm, HAINTZ legal, with whom we work closely. However, we also work together with other specialized law firms. We create public awareness Our PR efforts are effective. We have published hundreds of articles on SO DONE and similar cases. Many prosecutors, judges, and professors already reject the SO DONE construct. The tide must continue to turn – support us! Share, share, share. SO DONE will back down if we resist With your donation, you help us intensify our actions against the dishonest practices of SO DONE. Background: Since the "Schwachkopf" (Idiot) affair involving Federal Minister for Economic Affairs Robert Habeck, criminal charges filed by well-known politicians against ordinary citizens have become recognized as a societal problem. House searches over trivial matters, penalty orders for expressing opinions, and enrichment by leading politicians – all of this has become everyday reality in Germany. The main culprits behind this are reporting portals, particularly SO DONE, a platform with ties to the Free Democratic Party (FDP), which is responsible for thousands of criminal complaints against citizens through illegitime methods. This campaign aims to put an end to the unlawful activities of SO DONE and the politicians collaborating with the platform. For over a year and a half, our team has been fighting against SO DONE politically, legally, and in the media. We have published hundreds of articles on the issue, both on social media and on HAINTZ media. Our partner law firm, HAINTZ legal, manages hundreds of case files related to SO DONE and other legal and criminal proceedings involving politicians targeting citizens. We also collaborate with several other law firms to dismantle SO DONE's dishonest business model. We have already significantly restricted SO DONE’s business model through legal action and have made its activities widely known to the public. But that is not enough – we want to permanently and sustainably shut down this corrupt reporting platform for politicians. We need your support to achieve this goal. How we use your financial support: • Covering legal fees for victims of politically motivated complaints. • Supporting promising lawsuits and landmark cases against SO DONE and SO DONE legal. • Filing and funding criminal charges against high-ranking politicians, media figures, and celebrities in cases where authorities clearly apply double standards. • Investigating SO DONE from a tax law perspective. • Supporting media projects covering SO DONE, freedom of speech, political criminal charges, and reporting platforms in general. Legal Notice: We cannot issue donation receipts. Website (German), click here `,
  },
  {
    slug: "so-done-2",
    title: "YOUR Mission: SO DONE abschalten - Jetzt unterstützen!",
    goal: 100000,
    raised: 50000,
    image: "/images/so_done.webp",
    date: "February 12th, 2025",
    category: "Business",
    organizer: {
      name: "Markus Haintz",
      avatar:
        "https://images.gofundme.com/qHJ-ziLZSXPfibSDu1yCcsBZ8vo=/128x128/https://www.gofundme.com/person/profiles/df5fffa92b0f4cd4bbd825baa62d2738_edited_photo_1735957013454.jpeg",
      location: "Cologne, Nordrhein-Westfalen",
      contactPageLink: "https://google.com",
    },
    totalDonations: 333,
    totalRecentDonations: 45,
    recentDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    topDonation: {
      name: "Max Mustermann",
      amount: 500,
      avatar: null,
    },
    firstDonation: {
      name: "Max Mustermann",
      amount: 100,
      avatar: null,
    },
    featuredSection: {
      heading: "Your easy, powerful, and trusted home for help",
      title_1: "Easy",
      subtitle_1: "Donate quickly and easily",
      title_2: "Powerful",
      subtitle_2: "Send help right to the people and causes you care about",
      title_3: "Trusted",
      subtitle_3: "Your donation is protected by our Giving Guarantee",
    },
    description: `[English Version below] Politiker zeigen Bürger wegen vermeintlicher Beleidigungen an Schwachkopfaffäre, Hausdurchsuchungen und Geldstrafen, veranlasst durch Politiker. Was kannst Du aktiv für die Meinungsfreiheit tun? Du spendest! Du spendest, was es Dir wert ist, die Welt von unlauteren Meldeportalen wie "SO DONE" zu befreien, die von Politikern zu Lasten der Bürger und der Meinungsfreiheit missbraucht werden. Rechtliche Unterstützung, aktiv wie passiv! Wir bezahlen mit eurer Unterstützung Anwälte der Opfer von "SO DONE" in aussichtsreichen Zivil- und Strafverfahren bei zulässigen Meinungsäußerungen. Wir suchen die juristischen Angriffspunkte gegen "SO DONE" und nutzen sie. Keiner verfolgt aktuell so viele Fälle gegen "SO DONE" und die Politiker dahinter wie unsere Partnerkanzlei HAINTZ legal, mit der wir eng zusammenarbeiten. Wir arbeiten aber auch mit anderen spezialisierten Anwaltskanzleien zusammen. Wir sorgen für Außenwirkung Unsere PR wirkt. Wir haben hunderte Beiträge zum Thema "SO DONE" und Co. veröffentlicht. Viele Staatsanwaltschaften/Richter/Professoren stehen dem SO-DONE-Konstrukt bereits ablehnend gegenüber. Der Wind muss sich weiter drehen, hilf uns dabei. Teilen, Teilen, Teilen. "SO DONE" wird aufgeben, wenn wir uns wehren Mit Deiner Spende sorgst Du dafür, dass wir unsere Maßnahmen gegen die unlauteren Methoden von "SO DONE" intensivieren können. Zum Hintergrund: Spätestens seit der "Schwachkopf"-Affäre um Bundeswirtschaftsminister Robert Habeck sind Strafanzeigen von bekannten Politikern gegen einfache Bürger als gesellschaftliches Problem bekannt geworden. Hausdurchsuchungen wegen Banalitäten, Strafbefehle für Meinungsäußerungen, Bereicherung durch führende Politiker – all das ist inzwischen Alltag in Deutschland. Verantwortlich hierfür sind vor allem Meldeportale, und insbesondere das FDP-nahe Meldeportal SO DONE, das mit unlauteren Methoden für abertausende Strafanzeigen gegen Bürger verantwortlich ist. Diese Kampagne soll das rechtswidrige Treiben von SO DONE und den Politikern, die mit dem Meldeportal zusammenarbeiten, beenden. Seit eineinhalb Jahren geht unser Team politisch, juristisch und medial gegen SO DONE vor. Wir haben hunderte Beiträge zum Thema SO DONE veröffentlicht, auf Social Media und auf HAINTZ media. Unsere Partnerkanzlei HAINTZ legal führt hunderte Fallakten mit Bezug zu SO DONE und weiteren rechtlichen und strafrechtlichen Verfahren von Politikern gegen Bürger. Wir arbeiten auch mit mehreren anderen Anwaltskanzleien zusammen, um das unlautere SO-DONE-Geschäftsmodell zu beenden. Wir haben das Geschäftsmodell von SO DONE juristisch schon erheblich eingeschränkt und medial reichweitenstark einer großen Öffentlichkeit bekannt gemacht. Aber das reicht uns nicht: Wir möchten das unlautere Geschäftsmodell des Meldeportals für Politiker dauerhaft und nachhaltig beenden und SO DONE abschalten. Dafür benötigen wir auch Deine Unterstützung. Wir nutzen Deine finanzielle Unterstützung u. a. dafür, Opfern von Politikeranzeigen ihre Anwälte zu bezahlen. Wir fördern aussichtsreiche Prozesse/Musterprozesse gegen SO DONE und SO DONE legal. Wir erstatten und finanzieren Strafanzeigen gegen hochrangige Politiker, Medienvertreter und Prominente in Fällen, in denen die Strafverfolgungsbehörden offenkundig mit zweierlei Maß messen. Wir nehmen SO DONE steuerrechtlich unter die Lupe. Wir unterstützen Medienprojekte zu den Themen SO DONE, Meinungsfreiheit, Strafanzeigen durch Politiker und zu Meldeportalen allgemein. Rechtlicher Hinweis: Wir können keine Spendenquittungen ausstellen. ------------------------- english Version --------------------------------- Politicians report citizens for alleged insults „Schwachkopf“-Meme-Scandal, Raids and Fines Initiated by Politicians – What Can You Do to Defend Freedom of Speech? You donate! You donate what you think it's worth to free the world from illegitime reporting platforms like SO DONE, which are abused by politicians at the expense of citizens and freedom of speech. Legal support – Both active and passive! With your support, we pay for lawyers to defend the victims of SO DONE in promising civil and criminal cases involving permissible expressions of opinion. We identify legal attack points against SO DONE and use them to fight back. More information here No one is currently pursuing as many cases against SO DONE and the politicians behind it as our partner law firm, HAINTZ legal, with whom we work closely. However, we also work together with other specialized law firms. We create public awareness Our PR efforts are effective. We have published hundreds of articles on SO DONE and similar cases. Many prosecutors, judges, and professors already reject the SO DONE construct. The tide must continue to turn – support us! Share, share, share. SO DONE will back down if we resist With your donation, you help us intensify our actions against the dishonest practices of SO DONE. Background: Since the "Schwachkopf" (Idiot) affair involving Federal Minister for Economic Affairs Robert Habeck, criminal charges filed by well-known politicians against ordinary citizens have become recognized as a societal problem. House searches over trivial matters, penalty orders for expressing opinions, and enrichment by leading politicians – all of this has become everyday reality in Germany. The main culprits behind this are reporting portals, particularly SO DONE, a platform with ties to the Free Democratic Party (FDP), which is responsible for thousands of criminal complaints against citizens through illegitime methods. This campaign aims to put an end to the unlawful activities of SO DONE and the politicians collaborating with the platform. For over a year and a half, our team has been fighting against SO DONE politically, legally, and in the media. We have published hundreds of articles on the issue, both on social media and on HAINTZ media. Our partner law firm, HAINTZ legal, manages hundreds of case files related to SO DONE and other legal and criminal proceedings involving politicians targeting citizens. We also collaborate with several other law firms to dismantle SO DONE's dishonest business model. We have already significantly restricted SO DONE’s business model through legal action and have made its activities widely known to the public. But that is not enough – we want to permanently and sustainably shut down this corrupt reporting platform for politicians. We need your support to achieve this goal. How we use your financial support: • Covering legal fees for victims of politically motivated complaints. • Supporting promising lawsuits and landmark cases against SO DONE and SO DONE legal. • Filing and funding criminal charges against high-ranking politicians, media figures, and celebrities in cases where authorities clearly apply double standards. • Investigating SO DONE from a tax law perspective. • Supporting media projects covering SO DONE, freedom of speech, political criminal charges, and reporting platforms in general. Legal Notice: We cannot issue donation receipts. Website (German), click here `,
  },
];
